[project]
name = "meulade-rvsq"
version = "0.1.0"
description = "Automated RVSQ Appointment Finder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.3",
    "customtkinter>=5.2.2",
    "packaging>=25.0",
    "pillow>=12.0.0",
    "playwright>=1.57.0",
]
